osx_image: xcode7
language: objective-c
xcode_workspace: WordPressCom-Stats-iOS.xcworkspace
xcode_scheme: WordPressCom-Stats-iOS
xcode_sdk: iphonesimulator
sudo: false

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool